language: node_js
node_js:
  - 8
  - 9
  - 10
  - 11
  - 12
jobs:
  include:
    - stage: deploy
      node_js: 7
      script: echo "Deploying to npm..."
      deploy:
        api_key: 'D0cZYXDzT8zLjW1Pb/qFcrb/eAVHla/TXy0aWbxdXo2ncWcCa4kZ2CjMz/0M8/J8VCDViqxKvPaio+qXHj74zM3eJcdMuMC/Vq9pBEctgc3Uj8YRzdTYCNdR9Vtt3pPniTK4mTQFBTpG2JL4LJyTrtVMI3j6juoRs7dq+fEwrg6ggrHmGkUbmEg0HbomgD0CdElxRlPhILFjMzansssNF+3Hn4xDhRTnGzSpqlMGado5f8YeJ0HMafiJDTILUcw6Ey47aOMi/WIddzQJ2BaDfsiW0G37t8lOogx87yv/8nI3+d+uOYYMUlycJvfl+U+cDlyvofLn9oYs8UlpzIJ51f+gq3R3Cvjfphg9u5tthFZ5mbgJhF5kTZZrjKJp6PO+GrRY6BAcLDwtM+HSe9OGNu3WPf6aEdslZeUZtqnIoouFCoC4LQoRYWAoScAQxQMgkj2gTs8DK/fDZ+iw/JwZOd0KDAy1H/zYXVjXY9l0KwI84DQ0UID2iS/sJr2aWW0q35Y5gtAwkygZ9cmNlS8YnYWGudM25pkceRhMcL1MgK+MX/qp8aqGpPgxmDNp3e9qMotXbUJsEgDYzGgEToNUHO8Hz1R6LUXYIbcnn+Cy4XP3/MGJeWZ8gdbXRqelUNBjWan3ozp9OlQIvWF0CddyLuJTiEvJgsajMvh9c0m/atg='
        email: 'travis@0ti.me'
        on: master
        provider: npm
stages:
  - test
  - deploy
